/**
 * Core contract types for the Loykin resource runtime.
 * The contract mirrors the resource runtime design (see AGENTS.md).
 * This module must stay framework-free (no React imports).
 */

// ─── JSON Schema ──────────────────────────────────────────────────────────────

/** Structural alias — schema fragments are plain JSON Schema objects. */
export type JsonSchema = Record<string, unknown>

// ─── Resource envelope ────────────────────────────────────────────────────────

/** Tree-position-independent read of a named `dataflow` unit's current resolved value — resolved off the document-level DataflowEngine's snapshot, never a graph lookup, never scoped by render-tree ancestry. */
export interface DataflowRef {
  $dataflow: string
  path?: string
}

/** Points at a writable, object-shaped local runtime-state slot (see `Resource.objectState`) — backed directly by `RuntimeStore`, no fetch, no dependency graph. */
export interface ObjectStateRef {
  $state: string
  path?: string
}

export interface VariableRef {
  $variable: string
}

export type ValueBinding = ObjectStateRef | VariableRef

export interface Resource<TSpec = unknown> {
  /** Optional pointer to a file generated by `buildDocumentSchema` (human-editing-and-persistence.md #1) — lets editors like VS Code autocomplete/validate this document inline. Never validated as document content. */
  $schema?: string
  apiVersion: string
  kind: string
  metadata?: Metadata
  spec: TSpec
  /** Runtime-owned inputs declared by the kind's `bindingPolicy`. */
  bindings?: Record<string, ValueBinding>
  slots?: Slot[]
  /** Runtime-owned conditional rendering against one flat page variable. */
  visible?: VisibilityCondition
  /** Runtime-evaluated, kind-consumed: exposed via RenderContext, never gates rendering itself. */
  disabled?: VisibilityCondition
  /** Runtime-owned page variable declarations, scanned recursively across the whole document tree regardless of kind. */
  variables?: VariableDeclaration[]
  /** Runtime-owned event policy fallback, consulted when the kind's own `behaviorPolicy.events` doesn't cover the fired event. */
  events?: Record<string, EventPolicy>
  /** Only meaningful for a `recordScope: true` kind — the runtime resolves this to a single record and publishes it as `ctx.record`. */
  record?: DataBinding | ObjectStateRef
  /** Runtime-owned object-shaped local state declarations, scanned recursively across the whole document tree regardless of kind — the write-capable, structured counterpart to `variables` (flat strings only). See `ObjectStateRef`. */
  objectState?: ObjectStateDeclaration[]
  /** Runtime-owned, document-level named data-fetch declarations, scanned recursively across the whole document tree regardless of kind — see `DataflowUnit`. Read-only, tree-position-independent (unlike `record`, which is ancestor-owned and first-row-reduced). */
  dataflow?: DataflowUnit[]
  /** Runtime-owned, document-level named mutation declarations, scanned recursively across the whole document tree regardless of kind — the write-path counterpart to `dataflow`, but a passive lookup table only: never executed automatically, only on an explicit `runSubmit` call via a `MutationRef`. See `MutationUnit`. */
  mutations?: MutationUnit[]
}

export interface ObjectStateDeclaration {
  name: string
  initialValue?: unknown
}

/**
 * AI-authored server-state policy for a `dataflow` unit
 * (docs/dataflow-and-server-state-direction.md). Vocabulary is
 * resourcekit-generic, never a specific query library's option names —
 * `clampQueryPolicy` enforces the host's `QueryScopePolicy` ceiling on it.
 */
export interface QueryPolicy {
  refresh?: { kind: 'interval'; ms: number }
  staleForMs?: number
  retainPreviousData?: boolean
  retry?: { maxAttempts: number }
}

/**
 * A flat, document-level, named data-fetch unit. `binding` may reference
 * `${variables}` — it must NEVER reference another unit's resolved value (no
 * value-chaining; that boundary belongs to dashboardkit). `dependOn` is
 * execution-order/lazy-gating only: this unit does not attempt its fetch
 * until every named unit in `dependOn` has reached `ready`. Omitted/empty
 * `dependOn` makes this a root unit — it fetches eagerly as soon as the
 * document mounts, independent of whether any consuming kind is currently
 * rendered.
 */
export interface DataflowUnit {
  name: string
  binding: DataBinding
  policy?: QueryPolicy
  dependOn?: string[]
}

export type VisibilityCondition =
  | { $variable: string; equals?: never; contains?: never }
  | { $variable: string; equals: string; contains?: never }
  | { $variable: string; contains: string; equals?: never }
  | { $and: VisibilityCondition[] }
  | { $or: VisibilityCondition[] }
  | { $not: VisibilityCondition }

export interface Metadata {
  name?: string
  labels?: Record<string, string>
  annotations?: Record<string, string>
}

/** Parent-owned placement group. `name` is omitted for the default slot. */
export interface Slot {
  name?: string
  items: Resource[]
}

// ─── Slot policy ──────────────────────────────────────────────────────────────

export interface SlotPolicy {
  defaultSlot?: SlotRule
  slots?: Record<string, SlotRule>
}

export interface SlotRule {
  min?: number
  max?: number
  /** Allowed child kind names. Omit to accept any registered kind. */
  accepts?: string[]
  /**
   * Allowed child composition levels (see `KindManifest.level`). A
   * child matches if its `level` intersects this set. Unions with `accepts`
   * — a child is allowed if it matches either. Omit both to accept any
   * registered kind.
   */
  acceptsLevels?: string[]
  /**
   * What this slot is for, in plain language (e.g. "secondary filters and
   * navigation, rendered left of mainPane"). Surfaced as JSON Schema
   * `description` on the generated slot branch — the schema otherwise only
   * tells the AI which kinds are structurally valid here, not what the slot
   * means, which matters most when sibling slots accept the same levels.
   */
  description?: string
}

// ─── Behavior policy ──────────────────────────────────────────────────────────

export interface BehaviorPolicy {
  state?: 'internal' | 'external' | 'controlled'
  events?: Record<string, EventPolicy>
}

export interface BindingPort {
  description: string
  schema?: JsonSchema
  required?: boolean
  writable?: boolean
}

export interface BindingPolicy {
  inputs: Record<string, BindingPort>
}

export type EventPolicy =
  | { kind: 'internal' }
  | { kind: 'emit'; event: string }
  | { kind: 'action'; action: string }
  | { kind: 'setVariable'; variable: string; from?: string }

// ─── Variables ────────────────────────────────────────────────────────────────

export interface VariableDeclaration {
  name: string
  type?: 'string' | 'string[]'
  default?: string | string[]
  /** `url` syncs to a query param; `none` is transient UI state. Default: none. */
  persist?: 'url' | 'none'
}

export type VariableValue = string | string[] | undefined

// ─── Data bindings (read path) ────────────────────────────────────────────────

export interface DatasourceBindingSpec<TQuery = unknown> {
  datasourceUid: string
  datasourceType?: string
  query?: TQuery
  options?: Record<string, unknown>
  cacheTtlMs?: number
  staleWhileRevalidate?: boolean
}

export interface RestBindingSpec {
  url: string
  method?: 'GET' | 'POST'
  body?: unknown
  headers?: Record<string, string>
  /** JSON path to the rows array in the response, e.g. "data.items". */
  rowsPath?: string
}

export interface StaticBindingSpec {
  rows: Record<string, unknown>[]
}

/**
 * References a registered connection (see `ConnectionManifest`/`RegisteredConnection`
 * below) by UID instead of embedding a raw URL/DSN. `request` is opaque here —
 * its shape is defined by the connection's manifest (`ConnectionManifest.requestSchema`).
 */
export interface ConnectionBindingSpec {
  connection: string
  request: unknown
}

/**
 * Envelope shape mirrors `Resource`/`KindManifest` — `apiVersion`+`kind`
 * self-describe which registered `DataSourceManifest` resolves this
 * binding, `spec` is that manifest's own vocabulary. `valuePath` (a
 * dot-path applied by the runtime after the resolver returns rows) lives on
 * the envelope, not inside any variant's `spec` — it's a runtime-owned
 * concern applied uniformly regardless of source, same rule as
 * `variables`/`events`/`record` on `Resource`.
 */
export type DataBinding =
  | { apiVersion: string; kind: 'datasource'; spec: DatasourceBindingSpec; valuePath?: string }
  | { apiVersion: string; kind: 'rest'; spec: RestBindingSpec; valuePath?: string }
  | { apiVersion: string; kind: 'static'; spec: StaticBindingSpec; valuePath?: string }
  | { apiVersion: string; kind: 'connection'; spec: ConnectionBindingSpec; valuePath?: string }
  | { apiVersion: string; kind: string; spec: unknown; valuePath?: string }

export interface TimeRange {
  from: string
  to: string
  raw?: { from: string; to: string }
}

export interface DataResolveContext {
  variables: Record<string, VariableValue>
  timeRange?: TimeRange
  signal?: AbortSignal
  meta?: Record<string, unknown>
}

/**
 * v1 output contract is plain rows. Richer shapes (frames) are an additive
 * later union. `TSpec` narrows `binding.spec` for a resolver written against
 * one specific `DataBinding` kind (e.g. `DataResolver<RestBindingSpec>`);
 * left at its default `unknown`, `DataBinding & { spec: unknown }` collapses
 * back to plain `DataBinding` — the same signature used for a resolver
 * dispatched generically (by the registry, a coordinator) without knowing
 * any one binding kind's spec shape ahead of time.
 */
export type DataResolver<TSpec = unknown> = (
  binding: DataBinding & { spec: TSpec },
  ctx: DataResolveContext,
) => Promise<Record<string, unknown>[]>

/**
 * Self-describing registration for a `DataBinding` `kind` — mirrors
 * `KindManifest` (`apiVersion`+`kind` identify it, `specSchema` describes
 * its `spec`). Replaces the former separate `DataResolver`+
 * `DataSourceAdapter` split: every data source needs `resolve`;
 * `specSchema`/`resultSchema`/`queryKey` are optional enrichment
 * (docs/dataflow-and-server-state-direction.md P0 item 1) — `queryKey`
 * gives a `QueryCoordinator` a stable cache identity for a binding without
 * the coordinator having to understand source-specific request shapes,
 * falling back to a default key derivation when omitted. Unlike
 * `KindManifest<TSpec>`'s phantom `__spec` (erased by React's contextual
 * typing before it can narrow anything — see `render`), `TSpec` here is
 * live: it flows straight into `resolve`/`queryKey`'s `binding` parameter,
 * so a resolver written against one specific manifest (not placed inline in
 * a `ResourceKitPlugin.dataSourceManifests` array) reads `binding.spec`
 * pre-narrowed, no manual cast needed.
 */
export interface DataSourceManifest<TSpec = unknown> {
  apiVersion: string
  kind: string
  description?: string
  specSchema?: JsonSchema
  /** Shape of one resolved row — lets a scoped schema/prompt statically check `rowsPath`/`valuePath` dot-paths instead of the AI guessing them blind (generation-quality.md hallucination surface (a)). */
  resultSchema?: JsonSchema
  resolve: DataResolver<TSpec>
  queryKey?(binding: DataBinding & { spec: TSpec }, ctx: DataResolveContext): readonly unknown[]
}

// ─── Mutation bindings (write path) ──────────────────────────────────────────

export interface RestMutationSpec {
  url: string
  method?: 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  headers?: Record<string, string>
}

export interface DatasourceMutationSpec {
  datasourceUid: string
  mutation?: unknown
}

/** Envelope shape mirrors `DataBinding` — see its doc comment. */
export type MutationBinding =
  | { apiVersion: string; kind: 'rest'; spec: RestMutationSpec }
  | { apiVersion: string; kind: 'datasource'; spec: DatasourceMutationSpec }
  | { apiVersion: string; kind: string; spec: unknown }

/** Points at a document-wide, passively-declared `MutationUnit` — resolved once, synchronously, only inside `runSubmit`, never through `ctx.data.resolve`. No `path`: unlike `DataflowRef`, a mutation has no resolved value to sub-index into. */
export interface MutationRef {
  $mutation: string
}

/**
 * A flat, document-level, named mutation binding — the write-path
 * counterpart to `DataflowUnit`, but deliberately NOT engine-owned: no
 * fetch lifecycle, no caching, no `policy`, no `dependOn` — nothing async
 * to gate at declare time, since a mutation only ever runs on an explicit
 * `runSubmit` call, never automatically on document mount. `binding` may
 * reference `${variables}`/`${payload.x}` via the same interpolation
 * `runSubmit` already applies to an inline `SubmitSpec.mutation`; ref
 * resolution happens BEFORE that interpolation, so the declared binding may
 * itself still carry unresolved `${payload.x}` placeholders meant to be
 * filled in per call site. Like `DataflowUnit`, a unit's binding must never
 * read another unit's (mutation or dataflow) resolved value.
 */
export interface MutationUnit {
  name: string
  binding: MutationBinding
}

/** See `DataResolver<TSpec>` — same live-narrowing rationale, applied to `MutationBinding`. */
export type MutationResolver<TSpec = unknown> = (
  binding: MutationBinding & { spec: TSpec },
  payload: unknown,
  ctx: DataResolveContext,
) => Promise<unknown>

/** Self-describing registration for a `MutationBinding` `kind` — mirrors `DataSourceManifest`. */
export interface MutationSourceManifest<TSpec = unknown> {
  apiVersion: string
  kind: string
  description?: string
  specSchema?: JsonSchema
  resolve: MutationResolver<TSpec>
}

/**
 * Effect applied after a successful mutation.
 * setVariable: `value` sets a literal, `from` reads a dot-path from the
 * result, neither clears the variable (useful for closing popups).
 * emit: surfaces the mutation result to the host app (ResourceRenderer onEvent).
 * invalidateData/refetchData: docs/dataflow-and-server-state-
 * direction.md "Mutation과 invalidation" — a mutation-only screen isn't a
 * management screen without a way to tell affected dataflow units, by name,
 * to catch up.
 */
export type SubmitEffect =
  | { kind: 'setVariable'; variable: string; from?: string; value?: string | string[] }
  | { kind: 'emit'; event: string }
  | { kind: 'invalidateData'; dataflow: string[] }
  | { kind: 'refetchData'; dataflow: string[] }

/**
 * Declarative submit wiring for forms and editable cells:
 * an action name (gated by the scoped action allowlist), the mutation
 * binding to execute, and post-success effects. A variable touched by
 * `onSuccess` re-triggers dependent data bindings through normal reactivity.
 */
export interface SubmitSpec {
  action?: string
  mutation: MutationBinding | MutationRef
  confirm?: ConfirmSpec
  onSuccess?: SubmitEffect[]
}

// ─── Common spec fragments ───────────────────────────────────────────────────
// Shared vocabulary reused across view kinds (DetailView, TableView, ...) so
// field/filter/action syntax doesn't drift between them. See
// docs design note test.md §3.2.

export interface FieldSpec {
  field: string
  label?: string
  display?: 'text' | 'number' | 'date' | 'badge' | 'boolean'
  format?: string
  align?: 'left' | 'center' | 'right'
  emphasis?: 'normal' | 'strong'
}

export interface FilterSpec {
  name: string
  label?: string
  type: 'text' | 'select' | 'date' | 'dateRange'
  variable: string
  options?: Array<{ label: string; value: string }>
}

export interface ConfirmSpec {
  title: string
  description?: string
}

export interface RowCondition {
  field: string
  equals: unknown
}

interface ActionSpecBase {
  id: string
  label: string
  variant?: string
  hideWhen?: RowCondition
  disabledWhen?: RowCondition
}

export type ActionSpec = ActionSpecBase & ({ event: string; submit?: never } | { submit: SubmitSpec; event?: never })

/** Messages shown for a view's empty/error states; omitted fields fall back to the kind's default copy. */
export interface ViewStateSpec {
  emptyMessage?: string
  errorMessage?: string
}

// ─── Connections ──────────────────────────────────────────────────────────────
// See docs design note test.md §5. ResourceKit registers connection capability
// and dispatches through it; it never owns credential storage, connection
// pools, or query editing (test.md §5.1).

/** Registration-time request/method restrictions; adapter-specific shape. */
export interface ConnectionPolicy {
  methods?: string[]
  pathPrefixes?: string[]
}

/**
 * Per-connection MCP exposure limits (test.md §9). Capability flags default to
 * `true` for read operations (test/inspect/preview) and `false` for `mutate` —
 * write access must be opted into explicitly.
 */
export interface ConnectionMcpPolicy {
  test?: boolean
  inspect?: boolean
  preview?: boolean
  mutate?: boolean
  maxRows?: number
  timeoutMs?: number
  maxResponseBytes?: number
}

/**
 * A registered connection instance, e.g. `crm-api` — envelope mirrors
 * `Resource`/`KindManifest` (`apiVersion`+`kind` identify the registered
 * `ConnectionManifest` this instance is of). `config` carries
 * manifest-specific secrets/URLs and is never sent to MCP — see `ConnectionSummary`.
 */
export interface RegisteredConnection<TConfig = unknown> {
  uid: string
  apiVersion: string
  kind: string
  name: string
  description?: string
  config: TConfig
  policy?: ConnectionPolicy
  mcpPolicy?: ConnectionMcpPolicy
}

export interface ConnectionContext {
  signal?: AbortSignal
}

/**
 * Optional dynamic source of registered connections (test.md §12) — for hosts
 * that store connections in a database/API instead of pushing them into the
 * registry's static map via `registerConnection`. The registry checks its
 * static map first, then falls back to this provider.
 */
export interface ConnectionProvider {
  getConnection(uid: string): Promise<RegisteredConnection | undefined>
  listConnections(): Promise<RegisteredConnection[]>
}

export interface ConnectionTestResult {
  ok: boolean
  message?: string
  latencyMs?: number
}

export interface ConnectionInspectRequest {
  path?: string
}

export interface ConnectionInspection {
  schema?: JsonSchema
  fields?: Array<{ name: string; type?: string }>
  namespaces?: string[]
}

export interface RequestValidationResult {
  valid: boolean
  issues?: string[]
}

/** A capped, masked sample of what a request would return — never the full result set (test.md §7). */
export interface DataPreview {
  schema: JsonSchema
  rows: Record<string, unknown>[]
  stats?: {
    totalRows?: number
    returnedRows: number
    executionTimeMs?: number
  }
  truncated: boolean
}

/**
 * Self-describing registration for a connection *kind's* common request
 * vocabulary and execution (rest, datasourcekit, graphql, ...) — mirrors
 * `KindManifest`/`DataSourceManifest` (`apiVersion`+`kind` identify it,
 * `requestSchema` describes the request vocabulary). `resolve` is the
 * render-time path; MCP-facing `test`/`inspect`/`validate`/`preview` are
 * optional so manifests that don't support introspection can omit them
 * (see `ConnectionSummary.capabilities`).
 */
export interface ConnectionManifest<TConfig = unknown, TRequest = unknown> {
  apiVersion: string
  kind: string
  requestSchema: JsonSchema
  /** Shape of one resolved row, when known statically — see `DataSourceManifest.resultSchema`. Manifests whose result shape depends on the request (most connections) omit this; `preview`'s per-call schema is the fallback. */
  resultSchema?: JsonSchema

  test?(connection: RegisteredConnection<TConfig>, context: ConnectionContext): Promise<ConnectionTestResult>

  inspect?(
    connection: RegisteredConnection<TConfig>,
    request: ConnectionInspectRequest,
    context: ConnectionContext,
  ): Promise<ConnectionInspection>

  validate?(connection: RegisteredConnection<TConfig>, request: TRequest, context: ConnectionContext): Promise<RequestValidationResult>

  preview?(connection: RegisteredConnection<TConfig>, request: TRequest, context: ConnectionContext): Promise<DataPreview>

  resolve(connection: RegisteredConnection<TConfig>, request: TRequest, context: DataResolveContext): Promise<Record<string, unknown>[]>
}

/**
 * The MCP/AI-facing view of a registered connection — `config` (base URL, DSN,
 * credentials) is deliberately absent (test.md §5.3). `capabilities` is the
 * effective intersection of manifest capability ∩ connection `mcpPolicy` ∩
 * scope capabilities (test.md §6), computed by `ScopedRegistry.listConnections()`.
 */
export interface ConnectionSummary {
  uid: string
  apiVersion: string
  kind: string
  name: string
  description?: string
  requestSchema: JsonSchema
  resultSchema?: JsonSchema
  capabilities: {
    test: boolean
    inspect: boolean
    preview: boolean
    mutate: boolean
  }
}

// ─── Kind manifest ────────────────────────────────────────────────────────────

/**
 * `render` is framework-specific and therefore generic here. The react
 * adapter narrows TRender to its renderer signature. `load` supports lazy
 * (code-split) renderers — schema and validation never wait on it.
 */
export interface KindManifest<TSpec = unknown, TRender = unknown> {
  apiVersion: string
  kind: string
  specSchema: JsonSchema
  slotPolicy?: SlotPolicy
  behaviorPolicy?: BehaviorPolicy
  bindingPolicy?: BindingPolicy
  /**
   * Composition levels this kind is valid at (see docs/kind-level-taxonomy.md).
   * Most kinds carry exactly one tag; a kind that is both a whole-page
   * template and independently embeddable content (e.g. DataBody) carries
   * more than one. Used by `ScopeOptions.rootLevels` and `SlotRule.acceptsLevels`.
   */
  level?: string[]
  /**
   * What this kind is, in plain language, and — critically — when to use it
   * over a structurally similar sibling kind (e.g. DataBodyGroup vs.
   * DataBodySection vs. DataBodyTab all wrap children with a label/id and
   * are otherwise indistinguishable in the schema). Surfaced as JSON Schema
   * `description` on the kind's generated definition.
   */
  description?: string
  /**
   * When true, the runtime resolves `record` to a single record
   * (first row) before rendering children, and publishes it to descendants
   * as the nearest record scope (`ctx.record`, `fieldRef` reads).
   */
  recordScope?: boolean
  /**
   * When true, `registry.scope()` unconditionally drops this kind — even if
   * a scope's `kinds.include` explicitly names it. For kinds whose spec is
   * itself schema-shaped (e.g. a hypothetical `JSONSchemaForm`-style adapter
   * with an open `jsonSchema` property) rather than schema-*conforming*
   * data: exposing such a kind to AI/MCP generation would let the generator
   * define an arbitrary field set, bypassing the enumerable, reviewable kind
   * catalog `ScopedRegistry`/`kinds.include` exists to enforce
   * (provisr-poc-findings.md #9, docs/schema-shaped-kind-scoping.md). The
   * kind still renders normally when a host hand-authors it into a
   * document — this only affects the AI-facing scoped schema.
   */
  hostAuthoredOnly?: boolean
  /**
   * "This kind is used like this" — the minimal single-node teaching unit
   * (generation-quality.md hallucination surface (c) / example
   * infrastructure). Each example must independently pass `validateResource`
   * against a scope that includes this kind — CI enforces this via
   * `validateAllExamples`, so examples can't silently rot as the schema
   * evolves. Prompt assembly must only include examples an AI's actual
   * scope allows — see `ScopedRegistry.selectExamples`.
   */
  examples?: KindExample[]
  render?: TRender
  load?: () => Promise<TRender>
  /** Phantom member so TSpec participates in inference; never set at runtime. */
  __spec?: TSpec
}

export interface KindExample {
  description?: string
  resource: Resource
}

/**
 * A validated, composed multi-kind graph pattern (master-detail, filter +
 * table, form + submit) — teaches dependency/composition topology no single
 * kind's schema or example can (generation-quality.md hallucination surface
 * (c)). Registered independently of any one kind's `examples`.
 */
export interface PatternExample {
  name: string
  description?: string
  resource: Resource
}

// ─── Plugin ───────────────────────────────────────────────────────────────────

export interface ResourceKitPlugin<TRender = unknown> {
  name: string
  kinds?: KindManifest<unknown, TRender>[]
  patternExamples?: PatternExample[]
  /**
   * Self-describing `DataBinding` kinds (was the separate `dataResolvers`/
   * `dataSourceAdapters` records — merged since both were keyed by the same
   * source name). `DataSourceManifest<any>`, not `<unknown>`: this array is
   * deliberately heterogeneous (each manifest may be authored against its
   * own concrete `TSpec` standalone, then dropped in here) — `any` opts out
   * of variance checking for the array *position* while each manifest was
   * already checked at its own declaration site. `resolve`'s `binding`
   * parameter is contravariant, so this can't be `unknown` either — a
   * `DataResolver<StaticBindingSpec>` genuinely isn't assignable where a
   * `DataResolver<unknown>` (accepts any `DataBinding` kind) is expected,
   * and that rejection is correct: nothing but the registry's own
   * `apiVersion`+`kind` dispatch (invisible to the type system here)
   * guarantees `resolve` is only ever called with a matching-kind binding.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  dataSourceManifests?: DataSourceManifest<any>[]
  /** Self-describing `MutationBinding` kinds (was `mutationResolvers`) — same heterogeneous-array rationale as `dataSourceManifests`. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  mutationSourceManifests?: MutationSourceManifest<any>[]
  /** Self-describing connection kinds (rest, datasourcekit, ...) — not registered connection instances, see `ResourceRegistry.registerConnection`. */
  connectionManifests?: ConnectionManifest[]
}

// ─── Scoped capabilities ──────────────────────────────────────────────────────

export interface ScopeOptions {
  apiVersions?: string[]
  kinds?: {
    include?: string[]
    exclude?: string[]
  }
  /** Restricts which registered `dataSourceManifests` *kinds* this scope exposes. Omit to leave every registered kind visible (today's behavior). */
  dataSourceManifests?: {
    include?: string[]
    exclude?: string[]
  }
  /** Restricts which registered `mutationSourceManifests` *kinds* this scope exposes. Omit to leave every registered kind visible. */
  mutationSourceManifests?: {
    include?: string[]
    exclude?: string[]
  }
  /** Restricts which registered `connectionManifests` *kinds* (e.g. `rest`/`datasourcekit`) this scope exposes — distinct from `connections.allow`, which restricts connection *instances* by `uid`. Omit to leave every registered kind visible. */
  connectionManifests?: {
    include?: string[]
    exclude?: string[]
  }
  spec?: Record<
    string,
    {
      pick?: string[]
      omit?: string[]
      lock?: Record<string, unknown>
    }
  >
  slots?: Record<
    string,
    {
      include?: string[]
      exclude?: string[]
    }
  >
  variables?: {
    allow?: string[]
    lock?: Record<string, string | string[]>
  }
  datasources?: {
    allow?: string[]
  }
  actions?: {
    allow?: string[]
  }
  /** Restricts which registered connections (test.md §5.2) this scope exposes, and the capability ceiling applied to all of them (test.md §6). */
  connections?: {
    allow?: string[]
    capabilities?: {
      test?: boolean
      inspect?: boolean
      preview?: boolean
      mutate?: boolean
    }
  }
  maxDepth?: number
  /**
   * Allowed levels for the document root (see docs/kind-level-taxonomy.md).
   * The root is treated as the outermost implicit slot: a document is valid
   * only if its root kind's `level` intersects this set. Omit to leave the
   * root unrestricted (today's behavior).
   */
  rootLevels?: string[]
  /** Host ceiling applied to any `resolve` node's `QueryPolicy` (docs/dataflow-and-server-state-direction.md), see `clampQueryPolicy`. */
  queryPolicy?: QueryScopePolicy
}

/** Host-side limits a `QueryPolicy` is clamped against — never authored by the AI. */
export interface QueryScopePolicy {
  allowPolling?: boolean
  minIntervalMs?: number
  maxIntervalMs?: number
  maxRetries?: number
}

// ─── Staged schema requests ─────────────────────────────────────────────────
//
// Stateless "given what's already chosen, what's valid next" primitives.
// Intended to be called directly by whatever orchestrates generation (an MCP
// client's own tool-calling loop, a host application's own loop, etc.) —
// resourcekit deliberately doesn't ship an orchestration loop of its own; see
// docs/staged-generation-experiment.md for why.

/**
 * One position in the document tree to resolve — the root (omit `parent`),
 * or a specific slot on an already-chosen parent node.
 */
export interface StagePosition {
  parent?: {
    apiVersion: string
    kind: string
    /** Omit for the parent's defaultSlot. */
    slotName?: string
  }
}

/**
 * Result of resolving one `StagePosition`. Exactly one of `fixed`/`schema`
 * is set:
 * - `fixed`: this position has exactly one valid kind — insert it directly,
 *   no AI turn needed for the kind choice.
 * - `schema`: a self-contained JSON Schema (own `$defs`) scoped to just this
 *   position — envelope + spec for each candidate kind, not their slots.
 *   Recurse with a new `StagePosition` once a kind is chosen and its slots
 *   are known.
 */
export interface StageResult {
  fixed?: { apiVersion: string; kind: string }
  schema?: JsonSchema
}

/**
 * One already-resolved parent whose sibling slots should be resolved
 * together in a single request, instead of one `StagePosition` at a time.
 */
export interface StageBatchPosition {
  parent: { apiVersion: string; kind: string }
}

/**
 * Result of resolving every slot on a `StageBatchPosition.parent` at once.
 * - `fixed`: slotName -> the single valid kind for slots with no real
 *   choice — insert directly, no AI turn needed for these.
 * - `schema`: a self-contained object schema (own `$defs` where needed)
 *   covering every slot with real choice, one property per open slot name.
 *   Omitted if every slot is fixed or the parent has no slots. A
 *   non-repeatable slot's property is a candidate `oneOf` (envelope-only,
 *   no `spec`); a repeatable slot's property is a `oneOf`-item array with
 *   `minItems`/`maxItems`. Optional slots (`min` 0 or unset) are not in
 *   `required` — omitting the key means declining that slot.
 */
export interface StageBatchResult {
  fixed: Record<string, { apiVersion: string; kind: string }>
  schema?: JsonSchema
}

// ─── Validation ───────────────────────────────────────────────────────────────

export interface ValidationIssue {
  /** JSON-pointer-ish path into the document, e.g. "/slots/0/children/1/spec". */
  path: string
  /** What's wrong. */
  message: string
  /** An actionable, imperative instruction for fixing it — useful for both an LLM repair loop and a human editor (human-editing-and-persistence.md #2). */
  hint?: string
}

export interface ValidationResult {
  valid: boolean
  issues: ValidationIssue[]
}

// ─── Examples (generation-quality.md) ──────────────────────────────────────────

export interface SelectedKindExample {
  apiVersion: string
  kind: string
  description?: string
  resource: Resource
}

/** Result of `ScopedRegistry.selectExamples()` — only examples that pass `validateResource` against this exact scope. */
export interface SelectedExamples {
  kindExamples: SelectedKindExample[]
  patternExamples: PatternExample[]
}
